- README.md
Add documentation about the `nut.ups_event`
> Add documentation about the nut.ups_event

- README.md
- nut/config.json
- nut/rootfs/etc/cont-init.d/nut.sh
> Add new setting fake_usb_devices to enable faking USB devices to fix #24

- README.md
- nut/.README.j2
- nut/Dockerfile
- nut/config.json
- nut/rootfs/etc/cont-init.d/nut.sh
- nut/rootfs/etc/cont-init.d/nutclient.sh
- nut/rootfs/etc/fix-attrs.d/nut
- nut/rootfs/etc/services.d/upsd/run
- nut/rootfs/usr/bin/shutdownhost
Some small general tweaks and improvements for making it a stable release.
> :hammer: Tweaks and improvements

- LICENSE.md
- README.md
- nut/.README.j2
- nut/DOCS.md
> Happy New Year

- nut/Dockerfile
- nut/build.json
- nut/rootfs/var/run/nut/.gitkeep
Updates base image and relevant dependencies.
> ⬆Update base image to v9.0.1 and dependencies

- nut/DOCS.md
Update to reference integration, and remove references to setup in YAML
> 📚 Update docs to reflect integration

- nut/Dockerfile
- nut/build.json
https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2
> Upgrade add-on base image to 9.1.2

- .github/workflows/ci.yaml
> 🔨 Bump add-on linter to v2.0.0

- nut/config.json
Update add-on config for Supervisor 2021.2 (change usb and uart settings)
> 🔨 Update add-on config for Supervisor 2021.2

- nut/config.json
> 🔨 Enable udev in config

- nut/Dockerfile
> ⬆ Update net-snmp to 5.9-r2

- nut/config.json
> 🔨 Add sys_rawio to config

- nut/Dockerfile
- nut/build.json
- nut/config.json
⬇ Downgrade image and dependencies to v8.0.6
> ⬇ Downgrade image and dependencies to v8.0.6

- nut/DOCS.md
- nut/Dockerfile
- nut/build.json
- nut/config.json
- nut/rootfs/etc/cont-init.d/nut.sh
> 🔨 Change base image to Debian

- README.md
- nut/.README.j2
- nut/DOCS.md
Update rest of references to nut sensor/configuration.yaml
> 📚 Doc tweaks

- nut/DOCS.md
- nut/config.json
- nut/rootfs/etc/cont-init.d/nutclient.sh
- nut/rootfs/etc/nut/upsmon.conf
Add deadtime configuration option to allow more customisation of timeout options.
> 🔨 Add deadtime configuration option

- nut/DOCS.md
Fix indent formatting of options.
> 📚 Fix formatting

- nut/Dockerfile
- nut/build.json
Upgrades add-on base image to v4.2.0
> ⬆️Upgrades add-on base image to v4.2.0

- nut/Dockerfile
- nut/build.json
Upgrades add-on base image to v4.2.1
> ⬆️  Upgrades add-on base image to v4.2.1

- nut/Dockerfile
- nut/build.json
Upgrades add-on base image to v4.2.2
> ⬆️ Upgrades add-on base image to v4.2.2

- nut/Dockerfile
- nut/build.json
Upgrades add-on base image to v5.0.0
> ⬆️ Upgrades add-on base image to v5.0.0

- nut/Dockerfile
- nut/build.yaml
Upgrades add-on base image to 5.2.0
> ⬆️ Upgrades add-on base image to 5.2.0

- nut/Dockerfile
- nut/build.yaml
Upgrades add-on base image to 5.2.2
> ⬆️ Upgrades add-on base image to 5.2.2

- LICENSE.md
- README.md
- nut/.README.j2
- nut/DOCS.md
> 📚 Update Year 🎉

- nut/Dockerfile
- nut/build.yaml
Upgrades add-on base image to 5.2.3
> ⬆️ Upgrades add-on base image to 5.2.3

- nut/Dockerfile
- nut/build.yaml
Upgrades add-on base image to 5.3.0
> ⬆️ Upgrades add-on base image to 5.3.0

- .github/workflows/deploy.yaml
- nut/build.yaml
- nut/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

- nut/DOCS.md
Making things just a little more easier
> :books: Use new My Home Assistant link format

- nut/Dockerfile
- nut/build.yaml
> ⬆️ Upgrades add-on base image to 6.1.0

- LICENSE.md
- README.md
- nut/.README.j2
- nut/DOCS.md
> :fireworks: Updates maintenance/license year to 2023

- nut/Dockerfile
- nut/build.yaml
> ⬆️ Upgrades add-on base image to 6.2.3

- README.md
- nut/build.yaml
- nut/config.yaml
> Drop support for armhf & i386

- LICENSE.md
- README.md
- nut/.README.j2
- nut/DOCS.md
> :fireworks: Updates maintenance/license year to 2024

- LICENSE.md
- README.md
- nut/.README.j2
- nut/DOCS.md
> :fireworks: Updates maintenance/license year to 2025
